/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.systemcgl.screens;

import br.com.systemcgl.Fachada;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author zare
 */
public class MenuPrincipal extends javax.swing.JFrame {
    boolean isAdm;
    String id;


    Fachada f ;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public MenuPrincipal(boolean isAdm, String id, Fachada f) {
        this();
        this.f = f;
        this.isAdm = isAdm;
        this.id = id;
        UsuarioLabel2.setText(id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        Loca = new javax.swing.JButton();
        DevEquip = new javax.swing.JButton();
        Equipamentos = new javax.swing.JButton();
        Clientes = new javax.swing.JButton();
        Caixa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        UsuarioLabel1 = new javax.swing.JLabel();
        UsuarioLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        EditUser = new javax.swing.JMenu();
        Usuarios = new javax.swing.JMenuItem();
        jMenuEquip = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Systemcgl");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(95, 120, 150));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        Loca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/Shopping-Cart-42x42.png"))); // NOI18N
        Loca.setFocusable(false);
        Loca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Loca.setMaximumSize(new java.awt.Dimension(60, 60));
        Loca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Loca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocaActionPerformed(evt);
            }
        });
        jToolBar1.add(Loca);

        DevEquip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/computer-devolve-42x42.png"))); // NOI18N
        DevEquip.setFocusable(false);
        DevEquip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DevEquip.setMaximumSize(new java.awt.Dimension(60, 60));
        DevEquip.setMinimumSize(new java.awt.Dimension(50, 50));
        DevEquip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        DevEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevEquipActionPerformed(evt);
            }
        });
        jToolBar1.add(DevEquip);

        Equipamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/computer-42x42.png"))); // NOI18N
        Equipamentos.setFocusable(false);
        Equipamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Equipamentos.setMaximumSize(new java.awt.Dimension(60, 60));
        Equipamentos.setMinimumSize(new java.awt.Dimension(50, 50));
        Equipamentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Equipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipamentosActionPerformed(evt);
            }
        });
        jToolBar1.add(Equipamentos);

        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/Client-Male-Dark-42x42.png"))); // NOI18N
        Clientes.setFocusable(false);
        Clientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Clientes.setMaximumSize(new java.awt.Dimension(60, 60));
        Clientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(Clientes);

        Caixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/cash-register-42x42.png"))); // NOI18N
        Caixa.setFocusable(false);
        Caixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Caixa.setMaximumSize(new java.awt.Dimension(60, 60));
        Caixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaActionPerformed(evt);
            }
        });
        jToolBar1.add(Caixa);

        UsuarioLabel1.setText("Usuário:");

        UsuarioLabel2.setText("jLabel1");

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(UsuarioLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UsuarioLabel2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioLabel1)
                    .addComponent(UsuarioLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jToolBar1.add(jPanel1);

        jDesktopPane.setBackground(new java.awt.Color(113, 113, 113));

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Nova locação");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        EditUser.setText("Editar");

        Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/Edit-20x20.png"))); // NOI18N
        Usuarios.setText("Usuários");
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        EditUser.add(Usuarios);

        jMenuEquip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/Edit-20x20.png"))); // NOI18N
        jMenuEquip.setText("Equipamentos");
        jMenuEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEquipActionPerformed(evt);
            }
        });
        EditUser.add(jMenuEquip);

        jMenuBar1.add(EditUser);

        jMenu4.setText("Ferramentas");
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Ajuda");

        jMenuItem3.setText("Manual do Usuário");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocaActionPerformed
        // TODO add your handling code here:
       if(f.caixaIsOpen()){
        TelaLoca tl = new TelaLoca(jDesktopPane, f);
        tl.setVisible(true);
        jDesktopPane.add(tl);
        try {
            tl.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       }else {
           JOptionPane.showMessageDialog(this, "Você precisa abrir o caixa para efetuar essa operação");
       }
    }//GEN-LAST:event_LocaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        // Abre tela para editar usuários
       if (isAdm == true) {
            TelaUsers users;
            try {
                new TelaUsers(this).setVisible(true);
                this.setEnabled(false);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Você não tem permissão para efetuar essa operação");

        }
        
    }//GEN-LAST:event_UsuariosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);
                if (resp == JOptionPane.YES_NO_OPTION) {
                    this.dispose();
                    
                }
    }//GEN-LAST:event_formWindowClosing

    private void EquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipamentosActionPerformed
       
               TelaEquipamentos te;
        try {
            te = new TelaEquipamentos(jDesktopPane);
            te.setVisible(true);
            
            jDesktopPane.add(te);
            te.setMaximum(true);
            
        } catch (ClassNotFoundException | SQLException | PropertyVetoException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_EquipamentosActionPerformed

    private void jMenuEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEquipActionPerformed
        // TODO add your handling code here:
        this.EquipamentosActionPerformed(evt);
        
    }//GEN-LAST:event_jMenuEquipActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
        TelaClientes tc;
        try {
            tc = new TelaClientes(jDesktopPane);
            tc.setVisible(true);
            
            jDesktopPane.add(tc);
            tc.setMaximum(true);
           
        } catch (ClassNotFoundException | PropertyVetoException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ClientesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.formWindowClosing(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DevEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevEquipActionPerformed
        // TODO add your handling code here:

        TelaDevo td;

        try {
            td = new TelaDevo(f);
            td.setVisible(true);
            jDesktopPane.add(td);
        } catch (ClassNotFoundException | ParseException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_DevEquipActionPerformed

    private void CaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaActionPerformed
        // TODO add your handling code here:
        if (isAdm) {
            TelaCaixa tcaixa;
            tcaixa = new TelaCaixa(this, f);
            tcaixa.setVisible(true);
            this.setEnabled(false);
        } else {
            TelaAutenticacao ta;
            ta = new TelaAutenticacao(this,f);
            ta.setVisible(true);
            this.setEnabled(false);
            
        }
    }//GEN-LAST:event_CaixaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            // TODO add your handling code here:
           
          String dir = System.getProperty("user.dir");
          System.out.println(dir);
          java.awt.Desktop.getDesktop().open( new File(dir+"/Systemcgl_Manual.pdf") );
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Caixa;
    private javax.swing.JButton Clientes;
    private javax.swing.JButton DevEquip;
    private javax.swing.JMenu EditUser;
    private javax.swing.JButton Equipamentos;
    private javax.swing.JButton Loca;
    private javax.swing.JLabel UsuarioLabel1;
    private javax.swing.JLabel UsuarioLabel2;
    private javax.swing.JMenuItem Usuarios;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEquip;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    public Fachada getF() {
        return f;
    }

    public void setF(Fachada f) {
        this.f = f;
    }
}
