/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.systemcgl.screens;

import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author zare
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        Loca = new javax.swing.JButton();
        DevEquip = new javax.swing.JButton();
        CadEquip = new javax.swing.JButton();
        CadCliente = new javax.swing.JButton();
        Caixa = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        EditUser = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Systemcgl");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(95, 120, 150));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        Loca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/Shopping-Cart-42x42.png"))); // NOI18N
        Loca.setFocusable(false);
        Loca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Loca.setMaximumSize(new java.awt.Dimension(60, 60));
        Loca.setMinimumSize(new java.awt.Dimension(52, 52));
        Loca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Loca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocaActionPerformed(evt);
            }
        });
        jToolBar1.add(Loca);

        DevEquip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/computer-devolve-42x42.png"))); // NOI18N
        DevEquip.setFocusable(false);
        DevEquip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DevEquip.setMaximumSize(new java.awt.Dimension(60, 60));
        DevEquip.setMinimumSize(new java.awt.Dimension(50, 50));
        DevEquip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(DevEquip);

        CadEquip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/computer-add-42x42.png"))); // NOI18N
        CadEquip.setFocusable(false);
        CadEquip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CadEquip.setMaximumSize(new java.awt.Dimension(60, 60));
        CadEquip.setMinimumSize(new java.awt.Dimension(50, 50));
        CadEquip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CadEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadEquipActionPerformed(evt);
            }
        });
        jToolBar1.add(CadEquip);

        CadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/Add-Client-42x42.png"))); // NOI18N
        CadCliente.setFocusable(false);
        CadCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CadCliente.setMaximumSize(new java.awt.Dimension(60, 60));
        CadCliente.setMinimumSize(new java.awt.Dimension(52, 52));
        CadCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(CadCliente);

        Caixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/cash-register-42x42.png"))); // NOI18N
        Caixa.setFocusable(false);
        Caixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Caixa.setMaximumSize(new java.awt.Dimension(60, 60));
        Caixa.setMinimumSize(new java.awt.Dimension(52, 52));
        Caixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Caixa);

        jDesktopPane.setBackground(new java.awt.Color(113, 113, 113));

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Nova locação");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        EditUser.setText("Editar");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/Edit-20x20.png"))); // NOI18N
        jMenuItem4.setText("Editar usuários");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        EditUser.add(jMenuItem4);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/systemcgl/icones/Edit-20x20.png"))); // NOI18N
        jMenuItem3.setText("Editar equipamentos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        EditUser.add(jMenuItem3);

        jMenuBar1.add(EditUser);

        jMenu4.setText("Ferramentas");
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // Abre tela para editar usuários
        this.setEnabled(false);
       
        TelaUsers users = null;
        try {
            new TelaUsers(this).setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);
                if (resp == JOptionPane.YES_NO_OPTION) {
                    this.dispose();
                }
    }//GEN-LAST:event_formWindowClosing

    private void CadEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadEquipActionPerformed
        // TODO add your handling code here:
       // Dimension t = jDesktopPane.getSize();
       TelaCadEquip cadEquip = new TelaCadEquip();
       cadEquip.setVisible(true);
       jDesktopPane.add(cadEquip);
    }//GEN-LAST:event_CadEquipActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        TelaEquipamentos buscEquip ;
        try {
            buscEquip = new TelaEquipamentos(jDesktopPane);
            buscEquip.setVisible(true);
            jDesktopPane.add(buscEquip);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void CadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteActionPerformed
        // TODO add your handling code here:
        TelaCadCli tcc = new TelaCadCli();
        tcc.setVisible(true);
        jDesktopPane.add(tcc);
    }//GEN-LAST:event_CadClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadCliente;
    private javax.swing.JButton CadEquip;
    private javax.swing.JButton Caixa;
    private javax.swing.JButton DevEquip;
    private javax.swing.JMenu EditUser;
    private javax.swing.JButton Loca;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
