/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.systemcgl.screens;
import br.com.systemcgl.Fachada;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author zare
 */
public class TelaDevo extends javax.swing.JInternalFrame {
    private double valor;
    private int qtdDiasAtraso;
    private int codLocacao;
    private int codCliente;
    private Double multa;
    private Date dataAtual = new Date(System.currentTimeMillis());
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private Fachada f;
    /**
     * Creates new form TelaDevo
     */
    public TelaDevo() throws ClassNotFoundException, ParseException {
        initComponents();
        
    }

    public TelaDevo(Fachada f) throws ClassNotFoundException, ParseException{
        this();
        this.f = f;
        TabelaLocacao.setModel(DbUtils.resultSetToTableModel(f.mostraTabelaLoca()));
        dataAtual = sdf.parse(sdf.format(dataAtual));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaLocacao = new javax.swing.JTable();
        ConfirmarDevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelMulta = new javax.swing.JLabel();
        CampoBusca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);

        TabelaLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaLocacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaLocacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaLocacao);

        ConfirmarDevo.setText("Confirmar");
        ConfirmarDevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarDevoActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor da Multa:");

        labelMulta.setText("0.00");

        CampoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoBuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoBuscaKeyReleased(evt);
            }
        });

        jLabel1.setText("Pesquisa:");

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(3, 3, 3)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelMulta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cancelar)
                            .addGap(18, 18, 18)
                            .addComponent(ConfirmarDevo))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmarDevo)
                    .addComponent(jLabel2)
                    .addComponent(labelMulta)
                    .addComponent(Cancelar)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaLocacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaLocacaoMouseClicked
        // TODO add your handling code here:
        
        Date dataDevo;

        int seleciona = TabelaLocacao.getSelectedRow();
        codLocacao = Integer.parseInt(TabelaLocacao.getModel().getValueAt(seleciona, 0).toString());
        valor = Double.parseDouble(TabelaLocacao.getModel().getValueAt(seleciona, 4).toString());
        
         
        try {
            
            dataDevo = sdf.parse(TabelaLocacao.getModel().getValueAt(seleciona, 3).toString());
            qtdDiasAtraso = (int)((dataAtual.getTime() - dataDevo.getTime())/86400000);
            if (qtdDiasAtraso == 1){
                multa = 0.00;
            }
            multa = valor*qtdDiasAtraso;
            labelMulta.setText(multa.toString());
        } catch (ParseException ex) {
            Logger.getLogger(TelaDevo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_TabelaLocacaoMouseClicked

    private void ConfirmarDevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarDevoActionPerformed
        try {
            
            f.devEquip(codLocacao);
            JOptionPane.showMessageDialog(this, "Operação realizada com sucesso!");
            f.instaciaCaixa().somaSaldo(multa);
            this.dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TelaDevo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_ConfirmarDevoActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void CampoBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBuscaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscaKeyPressed

    private void CampoBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBuscaKeyReleased
        // TODO add your handling code here:
        String busca = CampoBusca.getText();
        try {

            TabelaLocacao.setModel(DbUtils.resultSetToTableModel(f.busca("loca", busca)));
            if (busca.equals("")) {
                TabelaLocacao.setModel(DbUtils.resultSetToTableModel(f.mostraTabelaLoca()));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CampoBuscaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoBusca;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton ConfirmarDevo;
    private javax.swing.JTable TabelaLocacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMulta;
    // End of variables declaration//GEN-END:variables

    public double getValor() {
        return valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

 
    

    public int getCodLocacao() {
        return codLocacao;
    }

    public void setCodLocacao(int codLocacao) {
        this.codLocacao = codLocacao;
    }

    public int getCodCliente() {
        return codCliente;
    }

    public void setCodCliente(int codCliente) {
        this.codCliente = codCliente;
    }
}
