/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.systemcgl.screens;
import br.com.systemcgl.Fachada;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author zare
 */
public class TelaLocaEquip extends javax.swing.JInternalFrame {
    DefaultTableModel modeloTelaAnterior;
    Fachada f= new Fachada();
    TelaLoca telaAnterior;
    Integer codEquip; 
    String nomeEq;
    
    String disponibilidade;
    
    double valoradd;
    

    //Objetos e variaveis da tela anterior
    private ArrayList<Integer> equipsList;
    private int qtdDias;
    private Double valor;
    private JTextField CampoValor;
    
    private JButton AddEquipsTelaAnterior;
    
    
    
    /**
     * Creates new form TelaLocaEquip
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public TelaLocaEquip() throws ClassNotFoundException, SQLException {
        initComponents();
        
        TabelaEquip.setModel(DbUtils.resultSetToTableModel(f.mostraTEquip()));
    }

    public TelaLocaEquip (int qtdDias, Double valor, TelaLoca ta, DefaultTableModel modelo, ArrayList<Integer> equipsList, JTextField CampoValor, JButton AddEquipsTelaAnterior) throws ClassNotFoundException, SQLException{
        this();
        telaAnterior = ta;
        this.modeloTelaAnterior = modelo;
        this.qtdDias = qtdDias;
        this.valor = valor;
        this.equipsList = equipsList;
        this.CampoValor = CampoValor;
        this.AddEquipsTelaAnterior = AddEquipsTelaAnterior;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaEquip = new javax.swing.JTable();
        Adicionar = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();

        setLayer(1);

        TabelaEquip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaEquip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaEquipMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaEquip);

        Adicionar.setText("Adicionar");
        Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarActionPerformed(evt);
            }
        });

        Fechar.setText("Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Fechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Adicionar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adicionar)
                    .addComponent(Fechar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        // TODO add your handling code here:
   
        
        CampoValor.setText(valor.toString());
        
        
        AddEquipsTelaAnterior.setEnabled(true);
        this.dispose();
        
    }//GEN-LAST:event_FecharActionPerformed

    private void AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarActionPerformed
        if (disponibilidade.equals("Não")) {
            JOptionPane.showMessageDialog(this, "Voce não pode adicionar um produto indisponível");
        } else {
            // atribui o nome e o codigo do equipamento , ambos como string
            equipsList.add(codEquip);
            modeloTelaAnterior.addRow(new Object[]{nomeEq});

            //Somar valores dos equipamentos
            if (qtdDias != 1) {
                valoradd *= qtdDias;
            }
            valor += valoradd;
            telaAnterior.setValor(valor);
            System.err.println("telaLocaequip valor "+valor);
        }
    }//GEN-LAST:event_AdicionarActionPerformed

    private void TabelaEquipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaEquipMouseClicked
        // TODO add your handling code here:
        String codTemp;
        
        String vltemp;
        int seleciona = TabelaEquip.getSelectedRow();
        codTemp = TabelaEquip.getModel().getValueAt(seleciona, 0).toString();
        nomeEq = TabelaEquip.getModel().getValueAt(seleciona, 1).toString();
        vltemp = TabelaEquip.getModel().getValueAt(seleciona, 5).toString();
        codEquip = Integer.parseInt(codTemp);
        valoradd = Double.parseDouble(vltemp);      
        disponibilidade = TabelaEquip.getModel().getValueAt(seleciona, 6).toString();
    }//GEN-LAST:event_TabelaEquipMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar;
    private javax.swing.JButton Fechar;
    private javax.swing.JTable TabelaEquip;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
